# Generated by Django 4.2.15 on 2024-08-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BgRemover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='remove')),
                ('created_at', models.DateField(auto_now=True)),
                ('result', models.ImageField(blank=True, null=True, upload_to='remove')),
            ],
        ),
    ]
